name: takens

channels:
- conda-forge

dependencies:
- python=3.10
- numpy
- matplotlib
- scikit-learn
- plotly
- pip
- tqdm
- ipywidgets
- openml
- pycairo
- scipy
- python-igraph
- numba

- pip:
  - giotto-tda
  - git+https://github.com/manu-mannattil/nolitsa.git
